/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'name' : string,
  'productId' : ProductId,
  'imageUrl' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface CartSummary {
  'items' : Array<CartItem>,
  'totalItems' : bigint,
  'totalPrice' : bigint,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
  'orderNumber' : string,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export type ProductId = bigint;
export type SessionId = string;
export interface ShippingAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'fullName' : string,
  'zipCode' : string,
  'state' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, bigint, string, string, string, bigint],
    Product
  >,
  'addToCart' : ActorMethod<[SessionId, ProductId, bigint], boolean>,
  'clearCart' : ActorMethod<[SessionId], undefined>,
  'createOrder' : ActorMethod<[SessionId, ShippingAddress], [] | [Order]>,
  'getCart' : ActorMethod<[SessionId], CartSummary>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'listProducts' : ActorMethod<[[] | [string], [] | [string]], Array<Product>>,
  'removeFromCart' : ActorMethod<[SessionId, ProductId], boolean>,
  'updateCartItem' : ActorMethod<[SessionId, ProductId, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];