/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const SessionId = IDL.Text;
export const ShippingAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
  'orderNumber' : IDL.Text,
});
export const CartItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : ProductId,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const CartSummary = IDL.Record({
  'items' : IDL.Vec(CartItem),
  'totalItems' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Product],
      [],
    ),
  'addToCart' : IDL.Func([SessionId, ProductId, IDL.Nat], [IDL.Bool], []),
  'clearCart' : IDL.Func([SessionId], [], []),
  'createOrder' : IDL.Func([SessionId, ShippingAddress], [IDL.Opt(Order)], []),
  'getCart' : IDL.Func([SessionId], [CartSummary], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'listProducts' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'removeFromCart' : IDL.Func([SessionId, ProductId], [IDL.Bool], []),
  'updateCartItem' : IDL.Func([SessionId, ProductId, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const SessionId = IDL.Text;
  const ShippingAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
    'orderNumber' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : ProductId,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const CartSummary = IDL.Record({
    'items' : IDL.Vec(CartItem),
    'totalItems' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Product],
        [],
      ),
    'addToCart' : IDL.Func([SessionId, ProductId, IDL.Nat], [IDL.Bool], []),
    'clearCart' : IDL.Func([SessionId], [], []),
    'createOrder' : IDL.Func(
        [SessionId, ShippingAddress],
        [IDL.Opt(Order)],
        [],
      ),
    'getCart' : IDL.Func([SessionId], [CartSummary], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([SessionId, ProductId], [IDL.Bool], []),
    'updateCartItem' : IDL.Func(
        [SessionId, ProductId, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };